// Package webfonts decides which of a site's theme fonts to load from a web
// font service (theme.web_fonts) and builds the <head> links for them.
//
// Both services take the Google Fonts CSS v1 syntax
// (`/css?family=A:400,700|B:400&display=swap`). That form skips the weights
// and styles a family lacks instead of failing the request, so the engine
// asks every family for the theme's full weight set and needs no per-family
// weight data: only the family names in families.tsv (generated by
// tools/webfonts-catalog). Browsers download only the faces a page uses.
package webfonts

import (
	_ "embed"
	"html"
	"strings"
	"sync"
)

//go:embed families.tsv
var familiesTSV string

// Providers are the accepted values of theme.web_fonts.
var Providers = []string{"google", "bunny"}

// Weights requested for every family: the weights the default theme uses
// (400 to 800) and the italics Markdown emphasis needs.
const Weights = "400,400i,500,600,700,700i,800"

type entry struct {
	name     string
	category string
}

var catalog = sync.OnceValue(func() map[string]entry {
	m := make(map[string]entry, 2048)
	for _, line := range strings.Split(familiesTSV, "\n") {
		name, category, ok := strings.Cut(strings.TrimRight(line, "\r"), "\t")
		if !ok || name == "" {
			continue
		}
		m[strings.ToLower(name)] = entry{name: name, category: category}
	}
	return m
})

// Lookup finds a family in the catalog, ignoring case. It returns the
// family's canonical name (the services match names case-sensitively) and
// its category: sans-serif, serif, display, handwriting or monospace.
func Lookup(name string) (canonical, category string, ok bool) {
	e, ok := catalog()[strings.ToLower(strings.TrimSpace(name))]
	return e.name, e.category, ok
}

// Generic and system font keywords: never a family to load or to quote.
var generic = map[string]bool{
	"serif": true, "sans-serif": true, "monospace": true, "cursive": true,
	"fantasy": true, "system-ui": true, "ui-serif": true, "ui-sans-serif": true,
	"ui-monospace": true, "ui-rounded": true, "emoji": true, "math": true,
	"fangsong": true, "-apple-system": true, "blinkmacsystemfont": true,
	"inherit": true, "initial": true, "unset": true, "revert": true,
}

// IsGeneric reports whether name is a CSS generic family or a system font
// keyword such as system-ui or -apple-system.
func IsGeneric(name string) bool {
	return generic[strings.ToLower(strings.TrimSpace(name))]
}

// PrimaryFamily returns the first named family in a CSS font stack, without
// its quotes, skipping generic keywords: `'Merriweather', Georgia, serif`
// gives "Merriweather" and `system-ui, sans-serif` gives "".
func PrimaryFamily(stack string) string {
	for _, part := range splitStack(stack) {
		if part != "" && !IsGeneric(part) {
			return part
		}
	}
	return ""
}

// StackHas reports whether a CSS font stack names family, compared whole and
// case-insensitively: `'Inter Tight', sans-serif` does not have "Inter".
func StackHas(stack, family string) bool {
	for _, part := range splitStack(stack) {
		if strings.EqualFold(part, family) {
			return true
		}
	}
	return false
}

// splitStack splits a font stack on the commas outside quotes, trimming each
// family and stripping its quotes.
func splitStack(stack string) []string {
	var parts []string
	var cur strings.Builder
	var quote rune
	flush := func() {
		parts = append(parts, strings.Join(strings.Fields(cur.String()), " "))
		cur.Reset()
	}
	for _, r := range stack {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			} else {
				cur.WriteRune(r)
			}
		case r == '\'' || r == '"':
			quote = r
		case r == ',':
			flush()
		default:
			cur.WriteRune(r)
		}
	}
	flush()
	return parts
}

// bundled fonts ship with the default theme and are never fetched.
var bundled = map[string]bool{"inter": true, "inter fallback": true, "jetbrains mono": true}

// fontTokens are the theme tokens that name a font, in output order.
var fontTokens = []string{"font-sans", "font-heading", "font-mono"}

// Families returns the canonical names of the catalog families the given
// token maps (resolved light and dark tokens) use as their primary font,
// without the bundled fonts, deduplicated and in a stable order.
func Families(tokenMaps ...map[string]string) []string {
	var out []string
	seen := make(map[string]bool)
	for _, tokens := range tokenMaps {
		for _, key := range fontTokens {
			name := PrimaryFamily(tokens[key])
			if name == "" || bundled[strings.ToLower(name)] {
				continue
			}
			canonical, _, ok := Lookup(name)
			if !ok || seen[canonical] {
				continue
			}
			seen[canonical] = true
			out = append(out, canonical)
		}
	}
	return out
}

func stylesheetBase(provider string) string {
	switch provider {
	case "google":
		return "https://fonts.googleapis.com/css"
	case "bunny":
		return "https://fonts.bunny.net/css"
	}
	return ""
}

// StylesheetURL is the one stylesheet URL that loads all the families from
// the provider, or "" for an unknown provider or no families. The families
// travel in a single `family=` parameter joined with `|`: Bunny's CDN keys
// its cache on the first `family=` only, so repeating the parameter can
// serve another site's fonts.
func StylesheetURL(provider string, families []string) string {
	base := stylesheetBase(provider)
	if base == "" || len(families) == 0 {
		return ""
	}
	specs := make([]string, len(families))
	for i, f := range families {
		specs[i] = strings.ReplaceAll(f, " ", "+") + ":" + Weights
	}
	return base + "?family=" + strings.Join(specs, "|") + "&display=swap"
}

// HeadLinks is the <head> markup for the families: preconnects to the
// provider's hosts, then the stylesheet. It returns "" when there is
// nothing to load.
func HeadLinks(provider string, families []string) string {
	url := StylesheetURL(provider, families)
	if url == "" {
		return ""
	}
	var sb strings.Builder
	switch provider {
	case "google":
		sb.WriteString(`<link rel="preconnect" href="https://fonts.googleapis.com">` + "\n")
		sb.WriteString(`<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>` + "\n")
	case "bunny":
		sb.WriteString(`<link rel="preconnect" href="https://fonts.bunny.net" crossorigin>` + "\n")
	}
	sb.WriteString(`<link rel="stylesheet" href="`)
	sb.WriteString(html.EscapeString(url))
	sb.WriteString("\">\n")
	return sb.String()
}
