package theme

// KnownTokens returns the set of all valid --sd-* token names (without the prefix).
// This must stay in sync with tokens.css — the TestKnownTokens_MatchesCSS test enforces this.
func KnownTokens() map[string]bool {
	return map[string]bool{
		// Primitives
		"white": true, "black": true,
		"gray-1": true, "gray-2": true, "gray-3": true, "gray-4": true, "gray-5": true,
		"gray-6": true, "gray-7": true, "gray-8": true, "gray-9": true,

		// Status hues
		"hue-accent": true,
		"hue-green": true, "hue-amber": true, "hue-red": true, "hue-cyan": true,
		"green": true, "green-low": true, "green-high": true,
		"amber": true, "amber-low": true, "amber-high": true,
		"red": true, "red-low": true, "red-high": true,
		"blue": true, "blue-low": true, "blue-high": true,
		"purple": true, "purple-low": true, "purple-high": true,

		// Extended hues
		"hue-blue": true, "hue-indigo": true, "hue-purple": true,
		"cyan": true, "cyan-low": true, "cyan-high": true,
		"indigo": true, "indigo-low": true, "indigo-high": true,

		// Semantic text
		"text": true, "text-muted": true, "text-subtle": true, "text-accent": true, "text-invert": true,
		"text-success": true, "text-warning": true, "text-danger": true,

		// Semantic backgrounds
		"bg": true, "bg-surface": true, "bg-nav": true, "bg-sidebar": true, "bg-footer": true, "bg-toc": true,
		"bg-inline-code": true, "bg-accent": true, "bg-accent-subtle": true, "hover": true,

		// Borders
		"border": true, "border-muted": true, "border-accent": true, "hairline": true,

		// Interactive
		"focus-ring": true,

		// Typography
		"font-sans": true, "font-mono": true,
		"text-xs": true, "text-sm": true, "text-base": true, "text-lg": true,
		"text-xl": true, "text-2xl": true, "text-3xl": true, "text-4xl": true, "text-5xl": true,
		"text-h1": true, "text-h2": true, "text-h3": true, "text-h4": true, "text-h5": true, "text-h6": true,
		"line-height": true, "line-height-headings": true, "line-height-relaxed": true,
		"weight-normal": true, "weight-medium": true, "weight-semibold": true, "weight-bold": true,
		"tracking-tight": true, "tracking-wide": true,

		// Spacing
		"space-1": true, "space-2": true, "space-3": true, "space-4": true, "space-5": true,
		"space-6": true, "space-8": true, "space-10": true, "space-12": true,

		// Radius
		"radius": true, "radius-sm": true, "radius-md": true, "radius-lg": true, "radius-xl": true, "radius-full": true,

		// Layout
		"nav-height": true, "sidebar-width": true, "sidebar-collapsed-width": true, "toc-width": true, "mobile-toc-height": true, "content-width": true, "docs-centered-width": true,

		// Z-index
		"z-header": true, "z-sidebar": true, "z-toc": true, "z-overlay": true, "z-modal": true, "z-toast": true, "z-sticky": true,

		// Transitions
		"transition-fast": true, "transition-normal": true, "transition-slow": true,
		"duration-100": true, "duration-150": true, "duration-200": true, "duration-700": true,
		"ease-default": true, "ease-out": true, "ease-bounce": true,

		// Shadows
		"shadow-xs": true, "shadow-sm": true, "shadow-md": true, "shadow-lg": true, "shadow-accent": true,

		// Code
		"code-bg": true, "code-text": true, "code-border": true, "code-font": true,
		"code-font-size": true, "code-line-height": true, "code-padding": true, "code-radius": true,
		"code-btn-size": true, "code-btn-bg": true, "code-btn-text": true,
		"code-btn-bg-hover": true, "code-btn-text-hover": true,

		// Glass
		"glass-bg": true, "glass-blur": true, "glass-border": true,

		// Motion
		"motion-lift": true, "motion-lift-lg": true, "motion-scale-sm": true,

		// Asides
		"aside-note": true, "aside-note-bg": true, "aside-tip": true, "aside-tip-bg": true,
		"aside-info": true, "aside-info-bg": true, "aside-caution": true, "aside-caution-bg": true,
		"aside-danger": true, "aside-danger-bg": true, "aside-success": true, "aside-success-bg": true,

		// Derived tokens (generated by DeriveTokens, not in tokens.css)
		"accent": true, "accent-hover": true, "accent-high": true, "accent-low": true,
	}
}

// SuggestToken returns the closest known token name if the edit distance is ≤ 2.
func SuggestToken(unknown string, known map[string]bool) string {
	best := ""
	bestDist := 3
	for name := range known {
		d := levenshtein(unknown, name)
		if d < bestDist {
			bestDist = d
			best = name
		}
	}
	return best
}

func levenshtein(a, b string) int {
	if len(a) == 0 {
		return len(b)
	}
	if len(b) == 0 {
		return len(a)
	}
	prev := make([]int, len(b)+1)
	curr := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		curr[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			curr[j] = min(curr[j-1]+1, min(prev[j]+1, prev[j-1]+cost))
		}
		prev, curr = curr, prev
	}
	return prev[len(b)]
}
